name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0  # ✅ Fixed Syntax
        with:
          server: ftpupload.net  # Your InfinityFree FTP host
          username: if0_38842714
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Change this if necessary
          server-dir: /htdocs/